config/routes.rb
Imapo::Application.routes.draw do
  resources :images
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  resources :users
  resources :sessions
  
  root :to => "images#index"
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :image, :user_id
  mount_uploader :image, ImageUploader

  validates_presence_of :image

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body

  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
    def not_authenticated
      redirect_to login_url, :alert => "First log in to view this page."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :require_login

  def index
    @images = Image.order("created_at desc").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def create
    @image = Image.new(params[:image])
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to root_path, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
      if user
        redirect_back_or_to root_url, :notice => "Logged in!"
      else
        flash.now.alert = "Email or password was invalid."
      end
  end

  def destroy
   logout
   redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:edit, :show]

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      # format.xml  { render :xml => @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        redirect_to root_path, :notice => 'User was successfully updated.'
        # format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        # format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        # format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/images/_form.html.erb
<%= form_for @image, :html => {:multipart => true} do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.file_field :image %>
  </div>
  <p>Please make sure you are only uploading a
    <strong>JPEG</strong>,
    <strong>JPG</strong>,
    <strong>PNG</strong>, or
    <strong>GIF</strong>. Otherwise your file will not upload.</p>
  <%= hidden_field_tag :image_user_id, current_user.id %>
  <p><%= f.submit "Upload Image" %></p>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<% @images.each do |image| %>
<div class="span3">
<div class="image-group">
<div class="image image-wrapper">
  <%= link_to image_tag(image.image_url(:thumb), :class => 'img-polaroid'), image %>
  <span class="admin-links"><i class="icon-remove icon-white"></i><%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure?' } %></span>
</div>
</div>
  <span>Highlight text below and copy it:
    <br />
    <input type="text" class="span3" name="image_url" value="<%= image.image_url %>" readonly>
  </span>
  </div>
<% end %>
<br />

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <div><%= link_to image_tag(@image.image_url(:thumb)), @image.image_url %></div>
  <p>Highlight text below and copy it:<br />
    <input type="text" class="span5" name="image_url" value="<%= @image.image_url %>" readonly>
  </p>
  <p><%= @image.image_url(:thumb) %></p>
</p>

<p>
  <b>User:</b>
  <%= @image.user.email %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Imapo", root_path, :class => 'brand' %>
<ul class="nav">
  <% if current_user %>
    <li>
      <%= link_to 'Upload Image', new_image_path %>
    </li>
    <li>
      <%= link_to 'Edit User', edit_user_path(current_user) %>
    </li> 
    <li>
      <%= link_to "Log out", logout_path %>
    </li>
  <% else %>
    <li>
      <%= link_to "Log in", login_path  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Imapo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Imapo" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>